### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by bjoernenders** [ptycho/ptypy#1]
I vote for permanently changing things in geometry: 

energy : stays , switch to electron Volts instead of keV or use actual SI unit. Actually the input here is not so super self explaining
z -> distance
psize_det -> psize or pixelsize
psize_sam -> resolution
N -> shape
lam -> we could decide to permanently discard this one. However a dumb user would mor likely put an SI unit here

**Comment by aaron-parsons** [comment]
I think this has been the case for a good while now. Closing...
