### ISSUE TITLE
Probe sharing between scans?

### ISSUE THREAD

**Issue by aaron-parsons** [ptycho/ptypy#105]
Hi folks,
I remember talking about this in the past, and I'm not sure if this is still a supported feature.
I have a case where I want to share a probe between two scans. From what I understand, to do this I should just set for instance: p.scans.scan_01.sharing.probe_shared_with = 'scan_00'.

However if I do this, I still get two sets of probes, one for each scan.

Does anyone have an example script I can look at where they have this working? I'm sure I've just missed something obvious.

Aaron

**Comment by bjoernenders** [comment]
Hi Aaron,
Yes it looks like you got it right. Could you post the script please?
The only example I know of currently is the object sharing one in the templates.
Best,
Bjoern

**Comment by aaron-parsons** [comment]
Aha. I shall have a check through this template first to make sure I didn't misunderstand.
________________________________

**Comment by bjoernenders** [comment]
It's the cSAXS pseudoBone script.

**Comment by aaron-parsons** [comment]
Thanks:-)

I'll write a reproducer using the sim module so it's similar to this.

If it's still a problem, I'll post the script.


________________________________

**Comment by aaron-parsons** [comment]
I can make it work when I use an example, so clearly I am doing something wrong in my version. I've added an example to the templates folder just so it's explicit for people who want to use it in future. It is only one parameter I guess, but it's there. See PR #106.
