### ISSUE TITLE
Ptypy hangs with 100% CPU usage

### ISSUE THREAD

**Issue by cmkewish** [ptycho/ptypy#108]
Tricky one: 

I have noticed that occasionally during DM iterations, ptypy will simply stop producing output. This infrequently happens but usually it is during a long mpi reconstruction of a large dataset. 

The CPU load doesn't change from its maximum value, but the process is completely hung and no further output is given. Leaving the computation running in this state for many hours after it should have completed, gives no result; nothing is output to disk and no progress is indicated beyond the hung iteration.

I'm not sure how to diagnose this, or provide any further verbosity that would indicate what could be the root cause. I have a reconstruction that is currently in that state, and with mpiexec on 24 cores, the load is averaging 36 out of 48 available cores, the RAM usage is at 28%, swap 0%, and the only diagnostic I have that seems high is ~250k CPU context switches/sec, but this may be due to the multiprocessing.

**Comment by alexbjorling** [comment]
It could be MPI deadlock, which can keep the CPU:s running at full speed,
https://stackoverflow.com/questions/35208163/comparing-cpu-utilization-during-mpi-thread-deadlock-using-mvapich2-vs-openmpi

Ptypy uses the simple Send which leaves it up to the implementation to decide whether to block execution or to buffer the message, perhaps with bigger data it will decide to block. Not sure how this applies to Allreduce (which is also used in DM).

Don't know how to diagnose either. If you can ctrl-C the process, I guess it will tell you where the KeyboardInterrupt happened.

**Comment by cmkewish** [comment]
Thanks for the tips Alex, I will look into this.

**Comment by cmkewish** [comment]
For the record, a ctrl+C doesn't provide any additional information, e.g.,
```
Iteration #242 of DM :: Time 183.29
Errors :: Fourier 1.58e+01, Photons 2.76e+00, Exit 1.07e-01
/data/xfm/staff/data/2017r2/Kewish_12123/analysisSXDM/lymph_node/155551_107/plots/ptypy_155551_107_256_77_to_40000/ptypy_155551_107_256_77_to_40000_DM_0242.png
^CCtrl-C caught... cleaning up processes

real	1482m26.671s
user	0m0.015s
sys	0m0.062s
```

**Comment by alexbjorling** [comment]
Oh I guess mpiexec catches the ctrl-c then. Right, I would start putting loads of print statements in the DM engine, especially before and after any MPI call (any call to parallel.xxx). But there's probably a more professional way to debug it.

**Comment by bjoernenders** [comment]
Without a reproducer, this currently cannot be debugged. Since I've not heard of this behavior anywhere else I suspect an issue with MPI at the compute site. Closing this for now.
