### ISSUE TITLE
unexpected probe-cropping behaviour (illumination.aperture)

### ISSUE THREAD

**Issue by simonesala** [ptycho/ptypy#112]
I noticed some (for me) unwanted behaviour within 'illumination.py'. If no aperture is specified in a launching script the default values are of course used within the probe preparation step which include aperture_size = None. However within the aperture function, when aperture_size is None a value of 1/3 is effectively used instead (cf <<dims = np.array(cgrid.shape) / 3.>>) which is supposedly designed to give a meaningful effect to a shaped aperture as it is applied to either one of 'rect' or 'circ' apertures - the latter is default.
The result of this is that when I'm initialising the probe or - even worse - when I'm loading an existing one (e.g. from a previous reconstruction) an unexpected aperture is applied on top of it, i.e. one which was not declared in the parameters tree nor hence desired.
My current workaround is to always specify an aperture size much larger than the expected field of view so that any aperture applied would have no effect on the prepared probe. I feel though that the behaviour I described should be either removed or stated explicitly somewhere.

**Comment by bjoernenders** [comment]
Hi Simone,
The parameter docs state, that if you set `aperture.form = None` there should be no aperture. Also the shortcut `aperture = None` should work as well although that is not a documented feature. The reason for not putting it into `aperture.size` is that this parameter intentionally accepts physical lengths.
Bjoern

**Comment by simonesala** [comment]
Thanks for the tips Bjoern: I must have missed the `aperture.form = None` info.
I checked and everything works as desired with `aperture = None`, i.e. there simply is no aperture in that case too.
I still believe that in order to avoid unexpected and unintended behaviour by default we should have `aperture = None` but I understand the code might have been designed like this with something else in mind - most likely the simulation of a supposedly universal decent initial guess for a circular illumination as default, I imagine.
