### ISSUE TITLE
clean up issues

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#121]
Now that we are almost converging on a 0.3 release candidate, a lot of old issues can be closed or updated with new info on actual choices made. This is a meta-ticket to do that.

**Comment by aaron-parsons** [comment]
Ok. I've done most of the one's I can now. Will go through them tomorrow with @pierrethibault  and @bjoernenders to make sure we can close this meta ticket. I've also started a project board for the 0.4 release, which is just a management tool to make it obvious what we are aiming for and who is working on what.
