### ISSUE TITLE
is client plotting going away?

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#125]
I have 3d Bragg running with DM now (!) and am currently plotting directly in `Ptycho` with matplotlib. I'm about to write a plotter that can deal with 3d data. Is any of the current zmq plotting funcionality (`MPLClient`, `PlotClient`, etc) going away any time soon? Any idea of what will remain and what is suitable to build upon?

**Comment by bjoernenders** [comment]
I would work of `PlotClient` . It makes most sense, MPL plotter may get replaced in future. Personally I would like to see the the plotting parameters disappear entirely from the input tree.

**Comment by alexbjorling** [comment]
Ok great, I've written something that holds a PlotClient instance and does its own thing. Cheers.
