### ISSUE TITLE
DM 3d suitable?

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#126]
A methodology question for you DM experts out there,

DM turns out to reconstruct my 3d Bragg data without modification. Is there any fundamental reason why this is wrong (like some assumptions, normalization, constants...) that implicitly assume two-dimensionality?

**Comment by bjoernenders** [comment]
Isn't that wonderful? The algorithm formulated in this abstract way has no implicit bias towards 2d I would think.

**Comment by alexbjorling** [comment]
I know it's pretty cool. Ok great!
