### ISSUE TITLE
Allow p.engine?

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#129]
Right now, the settings in for example `p.engine.DM` are not used, but they are also not rejected by `EvalDescriptor.validate`. I think we have a choice here, either we allow them (and then they need to be honoured) or we don't allow them (and then the descriptor should throw an error).

**Comment by aaron-parsons** [comment]
Just talked with Pierre about this, he doesn't really think it's needed. I'm ambivalent too.

@bjoernenders do you have any preference?

**Comment by aaron-parsons** [comment]
Bjoern agree with us.
