### ISSUE TITLE
is meta/common/info ok?

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#130]
I just noticed that minimal_load_and_run gives way worse reconstructions than minimal_prep_and_run. Does this mean that the meta/info business is still not OK, or is there a natural explanation?

**Comment by bjoernenders** [comment]
I cannot confirm that. The engines are different, e.g. one was using ML and there were different itterations throughout. And you are not using the 'file' loading option for PtydScan, meaning that the meta issues shouldn't have much of an affect. I harmonized the scripts now in f7807bf.

**Comment by alexbjorling** [comment]
Ah sorry I missed the obvious. Solved.
