### ISSUE TITLE
Write equivalent numpy "mini-kernels" (incl. method to convert between pods and numpy arrays)

### ISSUE THREAD

**Issue by aaron-parsons** [ptycho/ptypy#132]
This is the first step of the CUDA enhancement project. The idea is that small manageable parts will be rewritten into standard numpy calls, then ported into CUDA.

The contractor will look at using unified memory and streams to blend this (and memory transfers ) seamlessly into the existing architecture.

Work will be done on a CUDA branch, which will be taken off of the ocl branch.

**Comment by aaron-parsons** [comment]
This references: #31 #30

**Comment by alexbjorling** [comment]
Isn't it better to start this work after the 0.3 release? The ocl branch sits on top of master which is super outdated. What do you think @pierrethibault and @bjoernenders ?

**Comment by aaron-parsons** [comment]
Hi Alex. 

I wrote this ticket based on a conversation with Bjoern where he suggested to come off of the ocl branch.

However looking at the network graph I see you are completely right and that doing this will make everything very out of date with the release_candidate, which obviously has an entirely new way of handling PODs. 

I talked to Mark and what we propose is to make a branch off of the release candidate called "cuda". I will base this on the ocl branch but with updated methods. I'll keep the branch as up to date as possible with release candidate so that it doesn't diverge. Please shout anyone if you think this is a terrible idea. I'll start work on it now, but will keep it light-ish so we can change if you decide differently.

In the meantime, is there anything I can do to help the release go through? This is now the thing I will be spending the majority of my time on so if I can help I would like to.

**Comment by bjoernenders** [comment]
Hi all,

I just read this thread and will get back to you today with a suggestion. I am currently working on updating the documentation. However I think we should use the nd-classes branch and I will merge the release candidate into it to form a most recent branch that is able to build a the documentation. Once that is done, we need a brief discussion on how to handle the parameter tree which has diverged from an input based parameter tree to a module parameter tree and I have not formed an opinion yet.

Best Bjoern

**Comment by aaron-parsons** [comment]
Thanks Bjoern!

**Comment by bjoernenders** [comment]
Documentation is functional on the nd-classes branch, but I only checked for warnings and errors, not if the documentation makes sense. I probably would like some help with that, people looking for errors etc.

**Comment by aaron-parsons** [comment]
This side of things has been done, and the CUDA kernels written to match them. There are more tweaks needed, but I raise this in #149 . Closing this now.
