### ISSUE TITLE
Allow a ptypy executable to reconstruct from parameters provided in a yaml file

### ISSUE THREAD

**Issue by aaron-parsons** [ptycho/ptypy#133]
For some standard uses it would be tidier to be able to pass the parameters to a ptypy executable from a .yaml file rather than a script.

We could allow certain variables to be passed by executable one liners. 

This will then be converted into a u.Param tree by a utility.

**Comment by bjoernenders** [comment]
This sounds like a task for a separate script for ptypy/scripts. The descriptor class has the ability to change defaults via ArgParse. Maybe it's worth having a look there.

**Comment by aaron-parsons** [comment]
Validator has the provision built in for Json. We might go for that. Also descriptor has argparse options.
