### ISSUE TITLE
OPR scan model

### ISSUE THREAD

**Issue by aaron-parsons** [ptycho/ptypy#136]
Just talking this through with Pierre.
A new scan model needs to be created to take care of the OPR enhancements.
The current most up to date version of the OPR algorithms is on the I13_201705_PT branch. We plan to create a new branch off of release_candidate and just copy in the existing code that is required since the old branch is very out of date.

**Comment by aaron-parsons** [comment]
So the original merge now runs and after checking with the working plotting, seems to give a sensible result. We still can't get the saving to work so can't look further.

Next steps are:

- [x] Make saving work #135 
- [ ] Use new scan model

**Comment by bjoernenders** [comment]
OPR model has been implemented by now.
