### ISSUE TITLE
Multimodal reconstruction broken on release_candidate

### ISSUE THREAD

**Issue by aaron-parsons** [ptycho/ptypy#143]
I've found that on branches that are off of the release_candidate, and in release_candidate itself, if we set the number of probe modes>1 Ptycho falls over. I get the stack:

`
ptypy/test/template_tests/prep_and_run_DM_MF_multiple_probes_test.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ptypy/core/ptycho.py:314: in __init__
    self.init_data()
ptypy/core/ptycho.py:451: in init_data
    self.model.new_data()
ptypy/core/manager.py:967: in new_data
    new_data = scan.new_data()
ptypy/core/manager.py:305: in new_data
    new_pods, new_probe_ids, new_object_ids = self._create_pods()
ptypy/core/manager.py:777: in _create_pods
    geometry=geometry)  # , meta=meta)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ptypy.core.classes.POD object at 0x7f35b9e20980>, ptycho = <ptypy.core.ptycho.Ptycho object at 0x7f35ba9ea210>
model = None, ID = None
views = {'diff': <ptypy.core.classes.View object at 0x7f35bba1df50>, 'exit': <ptypy.core.classes.View object at 0x7f35b9e44890...k': <ptypy.core.classes.View object at 0x7f35b9e29050>, 'obj': <ptypy.core.classes.View object at 0x7f35b9e447d0>, ...}
geometry = <ptypy.core.geometry.Geo object at 0x7f35ba9ea7c0>, kwargs = {}
v = <ptypy.core.classes.View object at 0x7f35b9e29050>

    def __init__(self, ptycho=None, model=None, ID=None, views=None,
                 geometry=None, **kwargs):
        """
            Parameters
            ----------
            ptycho : Ptycho
                The instance of Ptycho associated with this pod.
    
            model : ~ptypy.core.manager.ScanModel
                The instance of ScanModel (or it subclasses) which describes
                this pod.
    
            ID : str or int
                The pod ID, If None it is managed by the ptycho.
    
            views : dict or Param
                The views. See :py:attr:`DEFAULT_VIEWS`.
    
            geometry : Geo
                Geometry class instance and attached propagator
    
            """
        super(POD, self).__init__(ptycho, ID, False)
        self.model = model
    
        # other defaults:
        self.is_empty = False
        self.probe_weight = 1.
        self.object_weight = 1.
    
        # Store views in V and register this pod to the view
        self.V = u.Param(self.DEFAULT_VIEWS)
        if views is not None:
            self.V.update(views)
        for v in self.V.values():
            if v is None:
                continue
            if v._pod is not None:
                # View has at least one POD connected
>               v.pods = weakref.WeakValueDictionary()
E               AttributeError: can't set attribute
`

I've created a branch "broken_multimodal" to investigate this.

**Comment by aaron-parsons** [comment]
Just took a look at this and fixed (1420cb81cefb700ad35202624537c893bd4d70f4) it so it now runs at least. I see two probes plotted. I need to get back to my desktop to check if this actually reconstructs properly so will do this tomorrow.

We are still getting a lot of issues with the parameter setting/ validation. I couldn't set up the diversity parameters because of a high limit that I was well within. I think it may be due to the join typing (tuple, float). I'll set up (or reactivate) another ticket to take a look at this.

**Comment by aaron-parsons** [comment]
Tested this on my desktop. Whilst the reconstruction runs, even with minimum blurring we don't get a good solution at all. this needs further investigating

**Comment by bjoernenders** [comment]
So I got the probe modes working again. Your example was never going to work unfortunately, because a psf of 5.0 for 92 frames at 128x128 is just way too much blurring. The severe bug in classes.py is on me though. Was easy to fix though.

**Comment by aaron-parsons** [comment]
Thanks! :-) Will take a look in the morning. I did try a wide range of PSF in the hope that I could get it to work. I guess that’s just what I left it at when I pushed.

________________________________

**Comment by aaron-parsons** [comment]
Thanks Bjoern. This works now as far as I can tell (works on GPU too!). I'll reopen if I discover we missed something but otherwise closing this for now.
