### ISSUE TITLE
Make a build matrix for Ptypy

### ISSUE THREAD

**Issue by aaron-parsons** [ptycho/ptypy#155]
We should make a build matrix for:
- min-deps
- mpi
- gpu
- nozmq

Core dependencies should be:
- numpy
- scipy
- h5py

Optional
- mpi4py (graceful fail)
- zeromq (warning)
- matplotlib (hard fail on submodule load)
- gpu (hard fail on submodule load)

Using travis where possible and the DLS jenkins server where not. For Jenkins tests we will push a token back to github so the state of the build (and build report?) are accessible outside of the network.

**Comment by aaron-parsons** [comment]
Ok so I've made this work now, on the build_matrix branch and you can see that the core_dependencies tests fail due to ZMQ. 
I've also added another environment yaml file for conda. If people just want the basic dependencies they now just have to do: 
conda env create --file core_dependencies.yml 

and for the full dependencies:

conda env create --file full_dependencies.yml

**Comment by bjoernenders** [comment]
Done. Closed with commit 83183dde78fa96408af633effe23d4c6066e3ba4
