### ISSUE TITLE
Limited GPU memory available for near-field ptychography calculations

### ISSUE THREAD

**Issue by jcesardasilva** [ptycho/ptypy#156]
I had a quick discussion with Pierre some months ago about the size of the files we acquire for near-field ptychography (NFP) and the limited memory available for commercial GPUs, which is typically 6GB for Titan, for example. NFP is very promising, but the calculation is the bottleneck, because it is too slow. So, GPU calculation would be crucial. I have even tried to use GPUs with other codes, but the main problem was to fit the data into the GPU's memory. 

We typically acquire 17 images of 2048x2048 pixels each and let us say they are 16 bits (~136 MB), which makes .ptyd files of about 173 MB. If for the ptypy reconstruction, we need 17 pods with Cprobe (2048x2048 complex64), Cmask (17x2048x2048 bool), Cexit (17x2048x2048 complex64), Cprobe (more or less 2200x2200 complex64), and Cdiff (17x2048x2048 float32), can we fit all these array into the GPU memory? Or are you thinking of doing something smarter for the memory management? And if we think of adding modes, the situation is even worst, so we are looking for possibilities.

I did not have the time to try the CUDA developments already done in one brunch, but how the memory is managed? 

Thank you in advance.

**Comment by aaron-parsons** [comment]
Hi,

So currently this is still a work in progress, and we aim to get something out for the next release (hopefully October).  The GPU enabled code has been designed to be a toolbox of CUDA enabled functions with cython wrappers. This means it has the best flexibilty at this level, and we plan to implement both synchronous and asynchronous MPI models for scenarios that don't fit in the memory of one card. For this case we are also looking at streams for overlapping some of the transfers, although this doesn't make sense for some of the kernels.

We also have optimised engines for when the data doesn't need to be transferred (which is obviously when you get the best speed up).

To give you an example of some quick benchmarking I did. On a far-field dataset with 45x2048x2048 we got a 91x speedup compared to a single CPU on one of our cluster nodes. I've not tried with nearfield yet, but will be doing so over the next few months. I'll give all the extra information when it's actually ready to share!

If you have some test data that is representative that you don't mind sharing, I can try to include that as part of some of my tests if it's helpful?

**Comment by jcesardasilva** [comment]
Hi Aaron, 

This is very good and interesting for us. 
I can share a dataset with you without telling what the sample is. The .ptyd file can be found here: https://drive.google.com/file/d/1uBJiDsfBcjjVykqxnbJek_frAyjPYpEV/view?usp=sharing

Please let me know if it works.

**Comment by daurer** [comment]
Nowadays, GPUs have more memory and as far as I am aware we can reconstruct standard nearfield-ptychography datasets with the latest GPU accelerated release (#393 )
