### ISSUE TITLE
New data viewer

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#16]
One nice idea would be to have a html5 client for real-time data visualisation and additional interactions such as pausing, changing parameters on-the-fly, etc.

**Comment by pierrethibault** [comment]
Jypiter could be a nice option. This project: https://github.com/jupyter-incubator/declarativewidgets could be a way of having both python interactivity and nice responsive GUI. 

See also the video: https://www.youtube.com/watch?v=SJiezXPhVv8 (minutes 25-35 and around 45).

**Comment by daurer** [comment]
We could also try combining jupyter with bokeh:
http://bokeh.pydata.org/en/latest/docs/user_guide/notebook.html

**Comment by bjoernenders** [comment]
This idea is addressed by the ptyweb viewer https://github.com/ptycho/ptyweb
