### ISSUE TITLE
Not importing all PtyScan subclasses causes problems.

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#162]
Commenting out all `experiment` submodules means that `ScanModel.makePtyScan` does not work anymore because it is looking for classes in `ptypy.experiment`. I suggest that we revert to the previous mechanism for the time being, possibly in a `try...except` block.

**Comment by pierrethibault** [comment]
I "solved" this by introducing a `register` decorator exactly like in engines (commit e5442eb). Still, I am not completely happy with this change. As it currently stands, the module containing the user-defined PtyScan subclass has to be explicitly imported prior to reconstruction, which means that reconstructions will run only in hand-edited scripts. I would prefer things to be more automatic, so would still recommend automatic import of all `experiment.*` submodules.

**Comment by pierrethibault** [comment]
... Just reintroduced the automatic import (commit 25b2b47).

Leaving this issue open to discuss this change.

**Comment by daurer** [comment]
@pierrethibault @bjoernenders where do we stand regarding automatic vs. explicit import of experiment (and engine) subclasses? I would be in favour of explicit imports in the user script. What are the arguments against this?

**Comment by daurer** [comment]
With release 0.5 we have again moved to explicit ptyscan imports in the user script. The main argument for this was that it protects us from any import issues in relation to non-standard dependencies that might be places inside user-defined ptyscan classes.
