### ISSUE TITLE
DM: calculation of mean power depends on MPI configuration

### ISSUE THREAD

**Issue by daurer** [ptycho/ptypy#168]
https://github.com/ptycho/ptypy/blob/094e272bf06d7e13757ece85c16969be2972853f/ptypy/engines/DM.py#L173

I have noticed that when running DM with MPI, the computed mean power is dependent on the number MPI processes used. This has an effect on the reconstructed object (depending on the MPI configuration)

**Comment by pierrethibault** [comment]
Should be fixed with e813350.
