### ISSUE TITLE
should pods just contain a conjugate array?

### ISSUE THREAD

**Issue by aaron-parsons** [ptycho/ptypy#174]
I'm looking into the overlap update in DM. For now this is just MPI on the CPU (I'll do the GPU later).

A quick profile of this method over 5 DM iterations shows the following:    

ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        5    0.000    0.000   34.907    6.981 DM.py:247(overlap_update)
        7   13.438    1.920   23.796    3.399 DM.py:358(probe_update)
        3    7.945    2.648   11.110    3.703 DM.py:297(object_update)
    10904    5.343    0.000    8.518    0.001 math_utils.py:22(cabs2)
    21794    6.499    0.000    6.499    0.000 {method 'conj' of 'numpy.ndarray' objects}
    54450    0.252    0.000    0.909    0.000 classes.py:1018(__getitem__)
    43560    0.031    0.000    0.765    0.000 classes.py:1350(data)
   475893    0.479    0.000    0.597    0.000 records.py:275(__getitem__)
    21780    0.169    0.000    0.489    0.000 classes.py:1050(__setitem__)
    18513    0.013    0.000    0.320    0.000 classes.py:2137(object)
    10890    0.029    0.000    0.288    0.000 classes.py:1908(__setitem__)

Which shows an awful lot of time doing conjugations (cabs2 is also a conj method call). 

Now I might be being stupid here, and we would have to be careful when we refreshed it, but would it make sense just to define another storage which was the probe.conj() and obj.conj() ?

This looks to save a decent fraction of time out of the calculation rather than calculating it when it's needed. It would increase the memory footprint, but for the CPU for HPC we don't really care at the moment.

What do we think?

**Comment by pierrethibault** [comment]
I have always found this part so annoying. There is nothing more simple than doing `a * b.conj()` but in python there is no way to do it without creating a temporary array with `b.conj()`. In my opinion the best way to optimise this would be to have a compiled version of `a * b.conj()`. A reasonable (and portable enough) way would be to define our own ufunc (e.g. https://docs.scipy.org/doc/numpy/user/c-info.ufunc-tutorial.html)

**Comment by aaron-parsons** [comment]
Hi Pierre. I see. So you think that most of the time in the conj() calculation is allocating the intermediate array (and that the ufunc would get rid of that overhead)?

**Comment by pierrethibault** [comment]
Is this solved?
