### ISSUE TITLE
deleting OPRmodel branch

### ISSUE THREAD

**Issue by simonesala** [ptycho/ptypy#175]
I'd soon like to delete the OPRmodel branch. @daurer and I are the main developers and users and moved to a new OPR branch.
Is there a way to make sure no one else still needs it (e.g. by getting in touch with anyone who pulled it in the past)?
I understand this is a private project, so this would otherwise still be rather straightforward.

**Comment by aaron-parsons** [comment]
What are your plans to merge with master/release_candidate?

________________________________

**Comment by simonesala** [comment]
The new OPR branch has been recently merged with release_candidate, so I guess we'll keep it up to speed with release 0.3. OPRmodel branch will become obsolete.

**Comment by pierrethibault** [comment]
No problem, as long as the only people working on it and with it have been informed.

**Comment by aaron-parsons** [comment]
Sorry, I mean: What are your plans for when will OPR be available in the release_candidate? It's not there now.

**Comment by pierrethibault** [comment]
Not ready for 0.3 that's for sure. I would think that 0.4 is realistic. We mostly need to sort out the ScanModel part.

**Comment by simonesala** [comment]
> No problem, as long as the only people working on it and with it have been informed.

This is exactly what I'm not sure how to do: do admins have a way to find out who pull-ed from OPRbranch in the past?

**Comment by wfeschen** [comment]
Hi Simone,

I used this branch to play a bit around with the OPR-Engine. For me this is fine. I think this is a really nice extension since we have some data where our probe changed during the scan. Using this method it showed us, that our pinhole, which we used to constrain the beam, drifted and therefore our probe changed.

Best,
Wilhelm

**Comment by bjoernenders** [comment]
Hi Simone,
I think you are referring to the last 3 weird dangling commits with a lot of diffs on them that you rather have no one use further. I think we could just delete the branch and you use OPR instead. There is unfortunately no way to avoid that people have pulled and incorporated this branch but chances are small if we act fast. Just go ahead and delete it.
Bjoern

**Comment by simonesala** [comment]
Good to hear OPR engine's usefulness's spreading already.
We'll keep developing things on the new OPR branch anyway, so any puller could just follow up on that.
