### ISSUE TITLE
parameter validation failed for engines

### ISSUE THREAD

**Issue by simonesala** [ptycho/ptypy#176]
I'm unable to trace back when and how the param tree changed.
I'm running a launching script that worked till earlier this summer, on OPR branch (near- up-to-date with release_candidate) and get this error:
```
  from ._conv import register_converters as _register_converters
WARNING root - Failed registering instance of <class 'ptypy.core.ptycho.Ptycho'> with ID Ptycho to object None
WARNING root - engines.engine_00                                  name                 UNKNOWN
ERROR root - engines.engine_00                                  symlink              INVALID
Traceback (most recent call last):
  File "ptypy_Scan018_MLOPR_46.py", line 166, in <module>
    P = Ptycho(p, level=5)
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/core/ptycho.py", line 318, in __init__
    defaults_tree['ptycho'].validate(self.p)
  File "/home/ss1r15/.local/lib/python2.7/site-packages/ptypy/utils/descriptor.py", line 984, in validate
    raise RuntimeError('Parameter validation failed:\n  ' + '\n  '.join(raise_reasons))
RuntimeError: Parameter validation failed:
  engines.engine_00 - make sure to specify the .name field
```
The problem being my launching script does include these lines:
```
p.engines = u.Param()
p.engines.engine_00 = u.Param()
p.engines.engine_00.name = 'MLOPR'
```
So I guess at least the error message should be refined.
How off am I from the expected param tree?

**Comment by aaron-parsons** [comment]
Hey. Does your engines.__init__.py have the import statement for  the opr engine?
________________________________

**Comment by pierrethibault** [comment]
Or is it the same as #167 (i.e. need to import the engine explicitly)?

**Comment by simonesala** [comment]
This was indeed very similar to #167, only with engines rather than scans.
I fixed it by importing the engine within my launching script.
Editing engines.__init__.py as @aaron-parsons suggested also works: do we want OPR engines on the release_candidate branch too? Otherwise I wouldn't mess with engines.__init__.py on OPR branch either.
Commit c1248388cbe78f630a7db30c9a62a94019575fed closed this issue.
