### ISSUE TITLE
Generous error catching causes severe confusion

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#186]
Just had a situation where a reconstruction worked on my laptop but failed like this on our cluster.

```
alebjo@fe0:~$ python /data/visitors/nanomax/common/config/basic_reconstruction_script.py
WARNING root - Failed registering instance of <class 'ptypy.core.ptycho.Ptycho'> with ID Ptycho to object None
WARNING root - scans.scan00.data                                  name                 UNKNOWN
ERROR root - scans.scan00.data                                  symlink              INVALID
Traceback (most recent call last):
  File "/data/visitors/nanomax/common/config/basic_reconstruction_script.py", line 72, in <module>
    P = Ptycho(p,level=5)
  File "/home/alebjo/.local/lib/python2.7/site-packages/ptypy/core/ptycho.py", line 311, in __init__
    defaults_tree['ptycho'].validate(self.p)
  File "/home/alebjo/.local/lib/python2.7/site-packages/ptypy/utils/descriptor.py", line 984, in validate
    raise RuntimeError('Parameter validation failed:\n  ' + '\n  '.join(raise_reasons))
RuntimeError: Parameter validation failed:
  scans.scan00.data - make sure to specify the .name field
```

Turns out there's nothing wrong with the parameter tree but that the PtyScan subclass wasn't imported. The reason for that is the very wide try/except clause in `experiment/__init__.py`, which stops all `PtyScan` loading because the `cSAXS`wants to import `fabio` that I didn't have on the cluster.

Shall we have individual try/except clauses for each experiment submodule?

**Comment by aaron-parsons** [comment]
Hi Alex,

The reason for this is that we are part way through making the ptyscan subclasses entirely plugin based. 

Bjoerns idea is that when you want to use a particular class, at the top of your script you will import that specific class. The reason for this is that the majority of imports we need will come from the bespoke libraries required by these classes, so to keep the package light, we just import the ones we need.

I like this, but it didn't make it through to this release, and was a last minute revert. Unless @bjoernenders objects, I think try/catch would be fine for now.

**Comment by alexbjorling** [comment]
Ah this rings a bell. But as it stands I can't run ptypy 0.3 on our cluster without installing fabio or messing with the `__init__.py`. Seems we need an intermediate solution.

**Comment by alexbjorling** [comment]
Acutally I'll just make a new nanomax branch to stop importing the cSAXS module. So closing this and referring to #167.
