### ISSUE TITLE
Overriding PtyScan parameters

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#190]
Sometimes a ptyd file's metadata (`distance`, `center`, ...) has to be tweaked. It would be good to have the possibility to override these parameters directly in the input script. For instance:
```python
p.scans.my_scan = u.Param()
p.scans.my_scan.name = 'Full'
p.scans.my_scan.data = u.Param()
p.scans.my_scan.data.name = 'PtydScan'
p.scans.my_scan.data.source = 'my_prepared_data.ptyd'
p.scans.my_scan.data.distance = 7.5 # instead of 6.5 in meta
```
To keep with the current way things are done, having `source = 'file'` still would not allow additional tweaking:
```python
p.scans.my_scan = u.Param()
p.scans.my_scan.name = 'Full'
p.scans.my_scan.data = u.Param()
p.scans.my_scan.data.name = 'PtydScan'
p.scans.my_scan.data.source = 'file'
p.scans.my_scan.data.dfile = 'my_prepared_data.ptyd'
p.scans.my_scan.data.distance = 7.5 # This field will be ignored
```

**Comment by pierrethibault** [comment]
Implemented.

**Comment by pierrethibault** [comment]
Some tests are now failing because of these lines:
https://github.com/ptycho/ptypy/blob/cab72ed2fb3359d35e44aa42f2a8f23285e82cd0/ptypy/test/ptyscan_tests/on_the_fly_ptyd_test.py#L66-L71
Passing `PtydScan.DEFAULT` to the `PtydScan` constructor including a `source` will override all of `meta`.
I would say that this is not a problem and that the test has to be modified, but happy to reconsider. My main problem is that I don't know how to do this. @aaron-parsons ?

**Comment by aaron-parsons** [comment]
Sure. I'll do this.

________________________________

**Comment by daurer** [comment]
It looks like this has been fixed. Closing the issue.
