### ISSUE TITLE
positions in ptyr output

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#196]
I'm making a new reconstruction viewer for the beamline. It's sometimes nice to overlay the scanning positions on the reconstruction. Any good reason that the positions are not saved to the ptyr file?

**Comment by aaron-parsons** [comment]
I don't think so. It's something I also want at some point. I guess we want the original positions + the final positions of the reconstruction if we have done position correction.

________________________________

**Comment by bjoernenders** [comment]
I don't object in having another saving type that saves the positions. But if your request is to just overlay the positions you can use the coordinate grid provided by the saved object storage and display the positions saved in the .ptyd file. That's how I usually do it. Works fine.

**Comment by alexbjorling** [comment]
No, finding the ptyd file is too complicated (for my users at least).
