### ISSUE TITLE
minimal script in tutorial is broken

### ISSUE THREAD

**Issue by daurer** [ptycho/ptypy#205]
It has been pointed out by @ningustc that the current tutorial is broken. The line 

https://github.com/ptycho/ptypy/blob/2dc39437b453de548ab8a4438f830b1730ee1e8a/tutorial/minimal_script.py#L74

causes a RuntimeError on validation of the parameter tree:

```
RuntimeError: Parameter validation failed:
   - scan
```

**Comment by pntbttrvbs** [comment]
submitted a PR for this. 

A quick fix is to just comment out the problem line.

Basically, when the Ptycho object is initialized, it's trying to validate the parameters. The validate method can't find the default for 'scan', which is set from the docstring by the defaults_tree.parse_doc decorator.

**Comment by bjoernenders** [comment]
Hi, yes the tutorial needs to be changed. Not the class. Thanks for pointing this out.

**Comment by daurer** [comment]
It seems like the tutorial has been fixed.
