### ISSUE TITLE
[INFO]: Deprecation spam after a recent upgrade of h5py, numpy, among others

### ISSUE THREAD

**Issue by cmkewish** [ptycho/ptypy#207]
Specifically, I upgraded a few packages within Anaconda recently, prompted by needing functionality from a later version of numpy than I was using for another task. Now there's a LOT of deprecation warnings, which spam useful data off the screen during iterations because they're verbose and issue once per cpu in use at the time.

For numpy:
`/opt/anaconda3/envs/pty03pc/lib/python2.7/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  'a.item() instead', DeprecationWarning, stacklevel=1)`

and for h5py I'm surprised to see that they wanted to kill `dataset.value`
`/opt/anaconda3/envs/pty03pc/lib/python2.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)`

and also:
`Saving to [...].ptyr
/user/home/.local/lib/python2.7/site-packages/ptypy/io/h5rw.py:99: H5pyDeprecationWarning: Deprecated; use special_dtype(vlen=basetype) instead`

for scipy:
`z[index] = x
/opt/anaconda2/lib/python2.7/site-packages/scipy/fftpack/basic.py:160: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use 'arr[tuple(seq)]' instead of 'arr[seq]'. In the future this will be interpreted as an array index, 'arr[np.array(seq)]', which will result either in an error or a different result.`

also the old matplotlib one has 'always' been there for me:
`/user/home/.local/lib/python2.7/site-packages/ptypy/utils/plot_client.py:509: MatplotlibDeprecationWarning: axes.hold is deprecated.`

This issue is non-breaking and mostly informational, for now, for me. I'm not sure whether this type of thing falls under the category of eventually deprecating python2 entirely, or if it's something worth keeping up with.

**Comment by alexbjorling** [comment]
> and for h5py I'm surprised to see that they wanted to kill dataset.value

I know, this `dataset[()]` is super ugly. 

I'm getting this more and more both with ptypy and for other code. Of course one should use virtualenvs and so on, but I can never be bothered so the outcome is terminal windows full of deprecation warnings everywhere...

**Comment by aaron-parsons** [comment]
Perhaps we could apply a filter for these which is linked to the verbosity level?

**Comment by aaron-parsons** [comment]
And as a long term, we should definitely be switching to python 3. Implementation to be discussed to maintain backwards compatibility.

**Comment by daurer** [comment]
Closing this issue since we have already moved to Python 3 and I am not aware that any of these warnings are still present.
