### ISSUE TITLE
rshayduk: Struggling to install PtyPy without success

### ISSUE THREAD

**Issue by rshayduk** [ptycho/ptypy#208]
I have tryied to install PtyPy as described in installation instructions on both, Windows and Linux systems without success.

On Windows I had troubles with pyqt4 and mpi4py

The installation on Linux, apparently, went fine, but, nevertheless the minimal script crashes on the first line:
>>> from ptypy import utils as u

with the report:

Traceback (most recent call last):
  File "minimal_script.py", line 1, in <module>
    from ptypy import utils as u
  File "/home/rshayduk/.local/lib/python2.7/site-packages/ptypy/__init__.py", line 37, in <module>
    import matplotlib
  File "/home/rshayduk/.conda/envs/ptypyenv/lib/python2.7/site-packages/matplotlib/__init__.py", line 111, in <module>
    import io
  File "/tmp/ptypy-master/ptypy/io/__init__.py", line 10, in <module>
    from .h5rw import *
  File "/tmp/ptypy-master/ptypy/io/h5rw.py", line 10, in <module>
    import h5py
  File "/home/rshayduk/.conda/envs/ptypyenv/lib/python2.7/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
  File "h5py/numpy.pxd", line 66, in init h5py.h5t
  File "/home/rshayduk/.conda/envs/ptypyenv/lib/python2.7/site-packages/numpy/__init__.py", line 145, in <module>
    from . import lib
  File "/home/rshayduk/.conda/envs/ptypyenv/lib/python2.7/site-packages/numpy/lib/__init__.py", line 24, in <module>
    from .npyio import *
  File "/home/rshayduk/.conda/envs/ptypyenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 14, in <module>
    from ._datasource import DataSource
  File "/home/rshayduk/.conda/envs/ptypyenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 226, in <module>
    _file_openers = _FileOpeners()
  File "/home/rshayduk/.conda/envs/ptypyenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 168, in __init__
    self._file_openers = {None: io.open}
AttributeError: 'module' object has no attribute 'open'

This looks to me like a corrupted installation of python27 and modules. I made a fresh install on a conda evironment (system environment is not allowed for users on that machine)

**Comment by bjoernenders** [comment]
Hello rshayduk,

thanks for reaching out. These reports are helpful to us. Unfortunately, we do not support Windows in any way. For Linux / conda, yes, it looks like something is wrong with your packages, as h5py / numpy combo seems broken for you. Have your tried standalone usage examples of h5py in combination with numpy?

In order to understand your issues, could you tell us the exact way you tried to install PtyPy with conda? I'll try to replicate your bug then. 

Also it would be great if you stated your name in the issue, so I'm not addressing a github handle.

Thanks,
Bjoern

**Comment by rshayduk** [comment]
Dear Bjoern,

thank you for the rapid response. I used pip install inside conda environment, that may have caused broken installation of essential packages.

I have re-installed all the packages like numpy, h5py, matplotlib, scipy etc. using:

conda install -n evnname packagename

It did only complain about pyqt4, that it can't be found on conda repository.

In fact, the minial reconstructino did run, showing a nice flower, that looked to me like magic!!

Here are the warnings:

"WARNING root - Could not import experiment cSAXSScan from cSAXS, Reason: No module named fabio
WARNING root - Failed registering instance of <class 'ptypy.core.ptycho.Ptycho'> with ID Ptycho to object None"

Regards, Roman.

**Comment by cmkewish** [comment]
FWIW, here is a list of steps I used to install PtyPy on a cluster of machines, starting from a fresh install of linux (three of the five machines were CentOS 7, two were Ubuntu 18.10):

```
# install some basic tools
sudo yum install vim htop glances wget bzip2 git 

# install X11 forwarding
sudo yum install xorg-x11-server-utils xorg-x11-xauth
sudo vim /etc/ssh/sshd_config
    
# disable and stop firewall
sudo systemctl disable firewalld
sudo systemctl stop firewalld

# disable SELinux
sudo setenforce 0
sudo vim /etc/sysconfig/selinux
    > SELINUX=disabled
sudo vim /etc/resolv.conf
    > search synchrotron.org.au beamline.synchrotron.org.au
    > nameserver <IP>
    > nameserver <IP>

# map DNS hostnames to IP addresses for cluster
sudo vim /etc/hosts
    > #MPI CLUSTER SETUP
    > <IP>    asciproto01
    > <IP>    asciproto02
    > <IP>    asciproto03
    > <IP>    asciproto04
    > <IP>    asciproto05

# install mpi
sudo yum install mpich

# create hosts file for mpiexec
vim ~/hosts
    > #HOSTS file for mpiexec
    > asciproto01:30
    > asciproto02:30
    > asciproto03:30
    > asciproto04:30
    > asciproto05:30

# generate SSH keys, copy to other nodes, try passwordless SSH
sudo yum install openssh-server
ssh-keygen
ssh-copy-id -i ~/.ssh/id_rsa.pub asciproto02
ssh asciproto02
ssh-copy-id -i ~/.ssh/id_rsa.pub asciproto03
ssh asciproto03
ssh-copy-id -i ~/.ssh/id_rsa.pub asciproto04
ssh asciproto04
ssh-copy-id -i ~/.ssh/id_rsa.pub asciproto05
ssh asciproto05

# map a shared data directory across other nodes
sudo yum install nfs-utils
mkdir data
sudo mount -t nfs asciproto01:/home/user/data ~/data

# mount the fileserver too, for data access
sudo yum install sshfs
mkdir fsdata
vim ~/mount_fsdata.sh
    > #!/bin/bash
    > sshfs root@<IP>:/data/ ~/fsdata/
chmod a+x mount_fsdata.sh 
./mount_fsdata.sh 

# install conda for python 2.7
wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
chmod a+x Miniconda2-latest-Linux-x86_64.sh 
./Miniconda2-latest-Linux-x86_64.sh 
    > (yes - to init base environment via .bashrc)
source ~/.bashrc

# create virtual environment for ptypy
conda create -n pty03 python=2.7
conda activate pty03

# install dependencies for ptypy
conda install numpy scipy mpi4py matplotlib h5py pillow pyzmq
conda install -c conda-forge fftw pyfftw

# install ptypy
git clone http://github.com/ptycho/ptypy.git pty03
cd pty03
python setup.py install --user

# fix error in python: unable to find Qt bindings
pip uninstall matplotlib
python -m pip install --upgrade pip
pip install matplotlib

# disable HDF5 file locking (for SWMR) for all sessions/servers
vim ~/.bashrc
    > export HDF5_USE_FILE_LOCKING=FALSE
```

Then to execute a ptypy script, call `mpiexec` with options specifying the hosts file and number of processes, etc.:

`$ mpiexec -f ~/hosts -n 80 -ppn 16 -binding cpu:cores python ptypy_script.py`
