### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#23]
Many many tests should be added, especially for data preparation recipes and engines.

**Comment by stefanoschalkidis** [comment]
Hi all,

I've completed the unittests for classes.py #83 . Theses are very basic tests which check initialization and default parameters. Some things could be implemented a bit nicer, e. g. parameter verification via templates, but this is simply a first attempt to get things off the ground.

To run the unittests, just execute the following in your ptypy root directory:
`python -m unittest discover`

To get a more verbose output add -v at the end. To get the code coverage execute:
`coverage run -m unittest discover`

This can be exported as html using:
`coverage html -d ../ptypy-cov/`

In the directory ../ptypy-cov/ you will find index.html, which will give an overview of the coverage. classes.py should be at 78%. A value between 80% to 90% is recommended before refactoring. I highly suggest that we implement the unittests for all main modules before any major rewrites to the code as they ensure that core functionality does not break. The unittests should not be altered unless default parameters change or functionality is removed. In addition to checking the functions, tests from the user's perspective should also be implemented.

Let me know what your thoughts are on this issue.

**Comment by bjoernenders** [comment]
We do have unit tests now.
