### ISSUE TITLE
Running the unit tests

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#230]
I have what is probably a stupid question. In the `py2topy3` branch, I can't work out how to run all tests. The instructions in #23 don't work. Does anyone know?

```
alex@w-alebjo-pc-2:~/code/ptypy$ python3 -m unittest discover
/home/alex/code/ptypy/ptypy/engines/utils.py:25: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by jcesardasilva** [comment]
Hi Alex,

The point is that importing directly from collections is deprecated. One
should now import from collections.abc instead. Maybe the version of the
prompt_toolkit you have is not using the proper import. I would say that
you can try to upgrade the package prompt_toolkit to check if the problem
is solved.

**Comment by alexbjorling** [comment]
Ah but that's just a warning, but good point I've updated prompt_toolkit.

I just can't work out how to run the tests, even on master with 2.7. @aaron-parsons how do you do it?

**Comment by stefanoschalkidis** [comment]
Hi Alex,

The unittests are not run because the default search pattern for the dicover() method was altered in core_tests (see: https://docs.python.org/3.5/library/unittest.html#unittest.TestLoader.discover). You could try a pattern with the wildcard at the front.

**Comment by stefanoschalkidis** [comment]
Hi Alex,

I just ran the unittests on the master and the py2topy3 branches using `python -m unittest discover -p "*_test.py"` with the following outcome:

master on python 2.7.16:
`Ran 255 tests in 44.864s OK (skipped=36)`

py2topy3 on python 3.6.8:
`Ran 257 tests in 17.188s FAILED (failures=3, errors=74, skipped=34)`

Hope this helps pinpointing the required changes for the python 3 transition.

**Comment by alexbjorling** [comment]
Thanks Stefanos! That did the trick.
