### ISSUE TITLE
ePIE engine bug report

### ISSUE THREAD

**Issue by wfeschen** [ptycho/ptypy#250]
Hi,

I think that I found two bugs in the epie engine. I solved them in my commit (https://github.com/wfeschen/ptypy/commit/14a368172ec0858ca1a2a3028358a29b7bfb4e19). Unfortunately my commit is a bit messy since there are also other changes. So I give a short explanation of the changes.

1. Bug:
At some point the code was ported to python 3. This broke the EPIE engine for multiple processes. I went back to the old implementation of the __node(x, y) function and it worked fine.

```
        def __node(x, y):
            return ((x - xlims[0]) // dx
                    + layout[1] * (y - ylims[0]) // dy)

```
Should be replaced by 
```
        def __node(x, y):
            return (int((x - xlims[0]) / dx)
                    + layout[1] * int((y - ylims[0]) / dy))
```

2. Bug:
There was some problem with sending the pods between the different nodes. Some pods were marked as "destination" and "sending", which led to problems. I think I fixed the problem by simply adding a forloop during the preparation.

```
        for name, dest in destinations.items():
            if self.pods[name].active:
                # sending this pod, so add it to a temporary list
                sendpods.append(name)

            if dest == parallel.rank:
                # receiving this pod, so mark it as active
                self.pods[name].di_view.active = True
```
was replaced by

```
        for name, dest in destinations.items():
            if self.pods[name].active:
                # sending this pod, so add it to a temporary list
                sendpods.append(name)

        for name, dest in destinations.items():
            if dest == parallel.rank:
                # receiving this pod, so mark it as active
                self.pods[name].di_view.active = True
```

How to continue? Do you agree to my changes or did I miss something?

Best,
Wilhelm

**Comment by alexbjorling** [comment]
Hi Wilhelm,

I wrote this terrible sending around of pods, so I feel partly responsible...

Your fix (1) is good, the conversion to int is needed even with ``//`` of course. I would have used the ``//`` anyway to show that it's integer division we want, but it doesn't matter practically.

For bug (2), I can't see how making it two loops would change anything, but I might be missing something. Are you sure it makes a difference?

**Comment by wfeschen** [comment]
Hi Alex,

the problem for the second "bug" is a bit special and the change does not have to be accepted for the standard epie algorithm. So I extended the epie algorithm to the broadbandwidth case. This means, that multiple pods refere to the same di_view, and this may result in troubles here, since when you activate a di_view, you also activate all the other pods attached to this di_view. I hope you understand what I mean.

Best,
Wilhelm

**Comment by alexbjorling** [comment]
Ah but then your second fix makes sense I suppose. Write a pull request!
