### ISSUE TITLE
[branch pycuda] Parameter validation fails for 'nearfield' propagation in GPU

### ISSUE THREAD

**Issue by jcesardasilva** [ptycho/ptypy#319]
Hi, 

I noticed that, since this week, when using the branch `pycuda` with 'nearfield' dataset, running in my GPUS, I get a `RuntimeError`: 

```
RuntimeError: Parameter validation failed:
  engines.engine00 - make sure to specify the .name field
  engines.engine01 - make sure to specify the .name field
```

which does seem to appear with 'farfield' dataset. It also does not appears when using CPUs, for example, the only difference between `ptypy_i13_AuStar_nearfield_9p7keV.py` and `ptypy_i13_AuStar_nearfield_9p7keV_pycuda.py` is the engine name, one using `_pycuda` and the other not. And so, `ptypy_i13_AuStar_nearfield_9p7keV.py` runs well in CPU without the problem of parameter validation whereas running `ptypy_i13_AuStar_nearfield_9p7keV_pycuda.py` in GPUs bumps into the validation problem given above. 

Do you think something was changed recently in the PtyScan class or somewhere else which could have affected this for `nearfield` datasets in GPU only? 

I can tell you that I was using the branch `pycuda` for my nearfield ptycho calculations until February without any problem, but now, the same macros are not working anymore.

**Comment by daurer** [comment]
Hi,

Thanks for reporting this. The `pycuda` branch is currently still under heavy development, but we are working towards a new release which will include all the new GPU engines and a few more changes. 

One thing that we have changed is that the accelerated engines are not available by default anymore and need to be explicitely imported in your run script. In your example above, the script was simply lacking a `from ptypy.accelerate.cuda_pycuda.engines import DM_pycuda`. I have fixed this now on the `ptypy_i13_AuStar_nearfield_9p7keV_pycuda.py` template example.
