### ISSUE TITLE
Fix/update documentation

### ISSUE THREAD

**Issue by daurer** [ptycho/ptypy#347]
- [x] update release notes
- [x] remove outdated information (e.g. python 2)
- [x] remove from pycuda dependencies those bits that are needed for cufft
- [x] what about the minimal_save? grids/positions?
- [x] remove broken stuff (check tutorials)
- [x] clean up parameter tree
- [x] Add GPU acceleration information and explain new concepts (e.g. block model and acceleration)
- [x] css partly broken

**Comment by bjoernenders** [comment]
Parameter tree postponed to #398
