### ISSUE TITLE
Implement orthogonal probe relaxation

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#38]
Implement the method in http://dx.doi.org/10.1364/OE.24.008360

**Comment by pierrethibault** [comment]
DM implementation now on branch indep_probes (commit 3a03c9e). Will get started on ML next.

One unresolved issue is the important change of model (single probe -> multiple probes spread out among nodes), which breaks things down the road (e.g. not all probes are saved!). My feeling is that this feature can be merged in master only after an important change in model (cf. #49)  @bjoernenders, an opinion?

(edit to link issue on multi-pass model)

**Comment by bjoernenders** [comment]
I think this is done now.
