### ISSUE TITLE
Error when running "ptypy/examples/notebooks/moonflower_blockfull_dm_pycuda.ipynb"

### ISSUE THREAD

**Issue by Amirafsharm** [ptycho/ptypy#383]
Hi, I receive the following error when running "moonflower_blockfull_dm_pycuda.ipynb". 
However, the code works when I change the engine from "DM_pycuda" to "DM" or "EPIE"
![error](https://user-images.githubusercontent.com/18283639/146924894-a4f90caf-fc01-4e02-bbaf-8a25439fa13a.JPG)
.

**Comment by daurer** [comment]
@Amirafsharm  the examples/templates are still work in progress. If you change this line 
`from ptypy.accelerate.cuda_pycuda.engines import projectional_pycuda` to 
`from ptypy.accelerate.cuda_pycuda.engines import projectional_pycuda_stream` it should work again...

Alternatively, you can also import all the pycuda engines at once using:
```
import ptypy
ptypy.load_gpu_engines("cuda")
```

**Comment by daurer** [comment]
All examples and templates are soon going to be rearranged and tested (#346) as part of the final changes before release 0.5 (#261)
