### ISSUE TITLE
Bring doc/ back to main repository

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#41]
Documentation should evolve with the code, so they should live together.

**Comment by stefanoschalkidis** [comment]
Hi @bjoernenders ,

I would like to add a few things to the documentation, but I think it makes sense to include it in the main repository first. Do you want to take care of the merge? Otherwise I would simply download it and create a pull request.

Kind regards,
Stefanos

**Comment by pierrethibault** [comment]
(resolved with 769b42ec47)
