### ISSUE TITLE
The Richardson Lucy deconvolution in PtyScan is non-canonical

### ISSUE THREAD

**Issue by bjoernenders** [ptycho/ptypy#46]
The RL-deconvolution procedure in data.PtyScan consumes a dispropotionate amount of parameters and is non-canonical in its execution. I presume deconvolution has to happen before rebinning? Since the correction is non-linear and also not entirely "common" I very much advise to shift the deconvolution to a subclass. This step may require to outsource the rebinning part of prepocessing in a separate function.

**Comment by stefanoschalkidis** [comment]
The RL-deconvolution has now been removed from data.PtyScan and should be implemented in subclasses if required (see I13_nfp.py for example).
