### ISSUE TITLE
Unique location for default parameters 

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#47]
Currently, default parameters are stored at the beginning of multiple files. These parameters are also stored in the file `resources/parameter_descriptions.csv`.

This information should not be duplicated, and all defaults should be drawn from a unique point, the csv file. We should also consider introducing a more robust validation of the input parameters. Most of the code is ready in `utils/validator.py`.

All this might have to be done after the transition `Param` -> `treeDict` (issue #17)

**Comment by pierrethibault** [comment]
I'd like to know if someone has an opinion on alternative ways of doing this. I have been thinking about the possibility of registering parameter informations from each file/module. Something like

``` python
from utils import parameters
parameters.register(name='distance', type='float', default=1, shortdoc='...', longdoc='...', userlevel=2)
```

Or using YAML:

``` python
from utils import parameters
parameters.register("""
name: distance
type: float
default: 1
shortdoc: ...
longdoc: ...
""")
```

I have the feeling that this is better than a unique csv file. In particular, in this system `Engines` and `PtyScan` classes are easily included in the parameter documentation and validation. YAML is also quite readable. This approach might be easier to extend also, if for instance we want to phase in a new field, say for GUI behavior.

**Comment by bjoernenders** [comment]
I like that YAML type of registering parameters.
