### ISSUE TITLE
v0.7 - multi modes broken in DM / DM_pycuda / ML_pycuda engines.

### ISSUE THREAD

**Issue by kahntm** [ptycho/ptypy#474]
Hej ptypy community,

I recently upgraded to ptypy 0.7 and enjoy using the DM / ML / DM_pycuda and ML_pycuda engine with one probe and one object mode without any issues.

But I noticed an issue when using multiple probe modes together with the DM engine. While using multiple object modes works flawlessly, I encounter error messages, the moment I want to use more than one probe mode and the DM engine. 
![2_probe_modes_DM](https://user-images.githubusercontent.com/26224125/215279236-0c0adbb3-4de9-400a-be95-98b2a4992541.png)

With the ML engine, the use of multiple probe and multiple object modes works without any errors and seems to give meaningful results.

When using DM_pycuda, both the use of either multiple probe modes or multiple object modes does not result in an error, but instantly creates NANs in with the first iteration. 

When using ML_pycuda, the usage of multiple object modes works without issues. But the usage of multiple object modes throws an error:
![4_probe_modes_ML_pycuda](https://user-images.githubusercontent.com/26224125/215283071-d28a5b66-649b-4b46-a069-b62e032de5a6.png)

Any help / insights are appreciated. I hope it is not just my installation.

**Comment by daurer** [comment]
Thanks @kahntm for reporting this issue, it seems like this is a bug introduced by this [commit](https://github.com/ptycho/ptypy/commit/8b4a60d61a5ba60d850971bf62329c7f741a029f). I am working on a fix.

**Comment by daurer** [comment]
This has been patched with [v0.7.1](https://github.com/ptycho/ptypy/releases/tag/v0.7.1)
