### ISSUE TITLE
Smoothing kernel for ML_pycuda croaks with memory issues for values of 200

### ISSUE THREAD

**Issue by bjoernenders** [ptycho/ptypy#497]
This requires some investigation into the smoothing kernel. For certain sizes, shared memory doesn't work anymore.
MemoryError("Cannot run kernel in shared memory")
We need to figure out the limit and switch to a FFT method when the smoothing kernel gets too large.

@jcesardasilva

**Comment by jcesardasilva** [comment]
Thank you, @bjoernenders 

Just adding some bits of information to understand the issue, here are the messages I get when the error happens: 

<img width="976" alt="image" src="https://github.com/ptycho/ptypy/assets/11873140/85ee80fd-5944-4c52-ba85-8ed11390c0c6">

**Comment by ptim0626** [comment]
The shared memory size limit in the smoothing kernel is imposed [here](https://github.com/ptycho/ptypy/blob/4cce5ae6a57ef8ca923ace0a902e504f6430fb5e/ptypy/accelerate/cuda_pycuda/array_utils.py#L356), which is 48kb.  The 48kb, according to Nvidia, is for compatibility with different architecture (see for example [here](https://docs.nvidia.com/cuda/volta-tuning-guide/index.html#unified-shared-memory-l1-texture-cache)).

The 48kb, in my opinion, is quite conservative, it is for device with compute capability 2.x. P100 is 64kb; V100 is 96kb; H100 is 228kb! However, to enable a shared memory limit larger than 48kb, this requires an explicit [opt-in](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#shared-memory-7-x). It seems CuPy provides [a way](https://github.com/cupy/cupy/pull/2369) to do it, but not pycuda.

While gathering the numbers, according to [Nvidia](https://docs.nvidia.com/cuda/ada-tuning-guide/index.html#unified-shared-memory-l1-texture-cache), CUDA reserves 1kb per thread block for shared memory. So for guarding this, the limit can be set as something like `(<SHM_LIMIT>-1024) // 2`. 

EDIT: Sorry for my oversight! pycuda actually exposes the shared memory [opt-in](https://documen.tician.de/pycuda/driver.html#pycuda.driver.function_attribute) as well.

**Comment by jcesardasilva** [comment]
Hello everyone, 

According to my recent tests, the implementation of FFT-based smoothing in ML #504 through the PR WIP GPU seems not to work to solve the issue. It appears that the value of `smooth_gradient` cannot exceed 20, as it results in the same error. I am yet to investigate this further and determine if the proper functions are being called. I will provide an update, but most likely not before today's meeting.

**Comment by daurer** [comment]
Thanks @jcesardasilva do you have a traceback of the error message that your are getting? Thanks for further looking into this. Would be good to know what needs to be done to get this fixed...

**Comment by ptim0626** [comment]
Hello, I added a temporary fix to #504, hopefully it works now for your testing.

**Comment by jcesardasilva** [comment]
> Thanks @jcesardasilva do you have a traceback of the error message that your are getting? Thanks for further looking into this. Would be good to know what needs to be done to get this fixed...

In response to @daurer remark, I would like to present the traceback here and my sincere apologies for my delay in doing so. I have not yet tried the "temporary fix" proposed by @ptim0626 

Here is the traceback of the error message, which shows the new functions have not been called, apparently (am I doing something wrong?): 

![image](https://github.com/ptycho/ptypy/assets/11873140/499cf793-434f-47df-b73d-ff3823395736)

**Comment by daurer** [comment]
The current solution seems to fix the problem that was reported when using the smoothing preconditioner in ML_pycuda. But more work is need before this can be merged. 

- should also be implemented in ML_cupy
- should we provide both convolution-base and fft-based version and let user decide or silently replace with FFT version in pycuda/cupy engines?
- do we need a similar change in the object smoothing regulariser in DM etc.?

**Comment by daurer** [comment]
Since 0.8.1, FFT-based smoothing is available with option `smooth_gradient_method` in GPU-accelerated ML engines.
