### ISSUE TITLE
GUI for input parameters

### ISSUE THREAD

**Issue by pierrethibault** [ptycho/ptypy#50]
Something has been programmed already for this at TUM. To be investigated.

**Comment by aaron-parsons** [comment]
Way back when, we also had something in DAWN that might do this too. Do you know if it was ever tested with ptypy?

**Comment by bjoernenders** [comment]
@daurer Are there issues already for ptyweb? This issue could be moved there. It essentially just says that we should have a GUI for input parames, which I agree to. I'm closing this here.
