### ISSUE TITLE
An issue with Parameter sweep

### ISSUE THREAD

**Issue by Amirafsharm** [ptycho/ptypy#535]
When executing "moonflower_raar_parameter_sweep.ipynb", parameter sweeping works fine.
However, when I continue the parameter sweep for a next value of beta, it seems that `P.restore_state(name="initial")`  does not force the client to restart. 
It seems `P.restore_state(name="initial")` works only once.
I attached an executable notebook. 
[moonflower_raar_parameter_sweep_issue.ipynb.zip](https://github.com/ptycho/ptypy/files/14319144/moonflower_raar_parameter_sweep_issue.ipynb.zip)

**Comment by daurer** [comment]
@Amirafsharm thanks for testing the new parameter sweeping feature and reporting this issue. The problem only relates to the error metrics, everything else is properly reset. 

To fix this, we need to make sure the runtime dict in `restore_state` is saved as a copy not a reference. Will try to get a PR in for the next release.

In the meantime, you can get around the problem by always reseting the `P.runtime = u.Param()` yourself, like this

```
P.restore_state(name="initial")
P.runtime = u.Param()
```

**Comment by daurer** [comment]
I have made a fix in #536 which should make it into the next release (0.9)

**Comment by Amirafsharm** [comment]
Thanks. Your suggestion works.
