### ISSUE TITLE
Options for notifying members of changes to the repo

### ISSUE THREAD

**Issue by stefanoschalkidis** [ptycho/ptypy#55]
Hi all,

I quickly wanted to ask if there is a way for notifying the members of changes which might affect the way they use ptypy without raising an issue? For example, I replaced `from scripts import *` with `import scripts` in the corresponding **init** file in utils. I've modified the associated import statements in the repo already, but I would just like make everyone aware of it in case someone starts looking for something and wonder where it went.

**Comment by pierrethibault** [comment]
In my opinion issues fit perfectly well this purpose.

**Comment by stefanoschalkidis** [comment]
Question answered and changes reverted.
