### ISSUE TITLE
Creating a Container copy with different data type

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#56]
Is there an accepted way of creating a "copy" of a Container object, with the data type changed? I need a representation of a complex128 Container where the new Storages should instead be int or bool. The old data is not important, just the structure of the Container, so the new storages can be filled with zeros.

**Comment by pierrethibault** [comment]
Maybe @bjoernenders will tell us that there are problems deep under, but to me it looks fine to add a `dtype` argument in `Container.copy()` and `Storage.copy()`...

**Comment by bjoernenders** [comment]
Yeah ok that could be done.

**Comment by alexbjorling** [comment]
Great, will do this and file a PR.
