### ISSUE TITLE
Work with multiple matherials

### ISSUE THREAD

**Issue by TsynkPavel** [ptycho/ptypy#586]
As I understand it, work with several materials at once is not supported at the moment. The 'formula' field accepts only one value

Is it possible to support such functionality ?

Or maybe there are some undocumented tricks that will allow to do it ?

**Comment by daurer** [comment]
Yes, the 'formula' field can only take a single string for a given material. This string value is then used to query the [CXRO database](https://henke.lbl.gov/optical_constants/). 

If you want to construct a more complicated material that would require multiple queries to CXRO, I would suggest that you do so outside of ptypy and use the "model" parameter to integrate your complex material as an ndarray into ptypy.

Hope this helps!
