### ISSUE TITLE
ok to add beamline PtyScan subclasses?

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#64]
For testing and practise use, I've ended up doing a few specific PtyScan subclasses (for example for beamline 5.3.2.1 of the ALS). Is it OK to simply commit these to the master branch, or is it better to keep them in feature branches or even keeping them in my local repos?

The subclasses are based on individual data sets, and I can't be sure that they will work for all data from those beamlines, even if most specifics are handled by the recipes. On the other hand, it's annoying to have different things in too many different branches.

**Comment by bjoernenders** [comment]
I do not yet have a fix opinion about that. Ideally, scan classes should not need an entry to **init**.py and could just be added as is even to the master branch. If the class is not used often it may get kicked out later anyway.

**Comment by alexbjorling** [comment]
thanks!
