### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by simonesala** [ptycho/ptypy#69]
I often (seemingly randomly) get the following error at the end of a reconstruction, when ptypy tries to finalize (running in mpi).
<<
Error in sys.exitfunc:
OperationalError                          Traceback (most recent call last)
/usr/lib/python2.7/atexit.pyc in _run_exitfuncs()
     22         func, targs, kargs = _exithandlers.pop()
     23         try:
---> 24             func(*targs, **kargs)
     25         except SystemExit:
     26             exc_info = sys.exc_info()

/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in atexit_operations(self)
   3113         # this must be *before* the tempfile cleanup, in case of temporary
   3114         # history db
-> 3115         self.history_manager.end_session()
   3116 
   3117         # Cleanup all tempfiles left around

/usr/lib/python2.7/dist-packages/IPython/core/history.pyc in end_session(self)
    506             self.db.execute("""UPDATE sessions SET end=?, num_cmds=? WHERE
    507                             session==?""", (datetime.datetime.now(),
--> 508                             len(self.input_hist_parsed)-1, self.session_number))
    509         self.session_number = 0
    510 

OperationalError: database is locked
>>
That I remember of, this is just happening with OPR engines: @pierrethibault is this a known issue?
This doesn't not prevent ptypy from saving the result which I'm guessing is done correctly by the master core (i.e. it's ok, it just looks bad and random).

**Comment by simonesala** [comment]
I also often get the same kind of error upon launching the reconstruction, still with mpi, but regardless of the used engines (i.e. not only with OPR): namely << sqlite3.OperationalError: database is locked >> and this prevents it from starting. Relaunching it till it succeeds has been my quick-fix so far. Any better suggestions (especially as to where to look at for the possible source of the problem)?

**Comment by bjoernenders** [comment]
This interactive shell is causing quite some trouble. Do we have an on/off switch for that?

**Comment by bjoernenders** [comment]
Ok my patience with this interactive shell is over. It is just not stable. With commit 7221f8a the interactive shell is in a new submodule `debug`. That means that now you have to ACTIVELY import the debug module to get the IPython prompt in your scripts. Just add the explicit import

from ptypy import debug

in your scripts to reactivate it. The usual import "import ptypy" will no longer import the ipshell.
@pierrethibault , @stefanoschalkidis : You are mainly using this feature. Could you please report if everything works fine?

**Comment by simonesala** [comment]
Broken for me.
Running 'from ptypy import debug' just returns 'ImportError: cannot import name debug'. Am I correct in understanding the debug module is simply not installed?
Will look more into this.

**Comment by bjoernenders** [comment]
Hi Simone. 
Thanks for the feedback. Debug was simply not listed as module in setup.py. But it worked in interactive mode. Commit 590219a should have fixed that.
Bjoern

**Comment by bjoernenders** [comment]
Simone, please report if the bug still exist and close the issue if commit 590219a fixed the issue

**Comment by simonesala** [comment]
I haven't seen this issue any more, but I cannot close it as it is not even clear to me how the 'OperationalError: database is locked' had anything to do with the ipshell. I can confirm the latter is working though.
