### ISSUE TITLE
DM producing nonsense when numiter_contiguous > 1

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#72]
Like the title suggests, I only get sensible results from `DM` with `numiter_contiguous = 1`. Using higher values produces nonsensical images which start out OK in the first iteration but quickly diverge.

Here's `numiter_contiguous = 1` (50 iterations):
![scan33_dmml_numiter_contiguous_1_dm_0050](https://cloud.githubusercontent.com/assets/20105820/20882199/17e87566-bae0-11e6-8292-ec6b8c3544e0.png)

and this is `numiter_contiguous = 5` (also 50 iterations):
![scan33_dmml_numiter_contiguous_5_dm_0050](https://cloud.githubusercontent.com/assets/20105820/20882206/1f868f24-bae0-11e6-8f59-f07157c0acf3.png)

With ePIE it works for any value of the parameter, which makes me suspicious, but here's my input just in case. Can you see anything wrong with my input, or is it indeed a bug in DM?

~~~~
""" 
This script loads a ptyd file and starts a reconstruction. The idea
is that the ptyd file is generated on-the-fly, but it can of course be a
pre-made ptyd as well. 
"""

import ptypy
from ptypy.core import Ptycho
from ptypy import utils as u

scannr = 33
engine = ['DMML', 'EPIE'][0]

p = u.Param()
p.run = 'scan%d_%s_numiter_contiguous_1'%(scannr, engine)
p.verbose_level = 3

# geometry info only needed for changing propagator, I think. energy,
# distance, psize etc is saved in the ptyd.

# IO and plotting
p.io = u.Param()
p.io.home = "/home/alex/ptycho/Vogt_week48/scan%d/"%scannr

p.io.autoplot = u.Param()
p.io.autoplot.imfile = "plots/%(run)s/%(run)s_%(engine)s_%(iterations)04d.png" ## (17) Plot images file name (or format string)
p.io.autoplot.interval = 1						## (18) Number of iterations between plot updates
p.io.autoplot.threaded = True 					## (19) Live plotting switch
p.io.autoplot.layout = u.Param()				## (20) Options for default plotter or template name
p.io.autoplot.dump = True						## (21) Switch to dump plots as image files
p.io.autoplot.make_movie = False				## (22) Produce reconstruction movie after the reconstruction.

# Scan parameters (mostly illumination)
p.scans = u.Param()
p.scans.NM = u.Param()
p.scans.NM.data= u.Param()
p.scans.NM.data.source = 'file'
p.scans.NM.data.dfile ='scan%d.ptyd'%scannr
p.scans.NM.illumination = u.Param()
p.scans.NM.illumination.model = None
p.scans.NM.illumination.aperture = u.Param()
p.scans.NM.illumination.aperture.form = 'circ'
p.scans.NM.illumination.aperture.size = 300e-9

# Reconstruction parameters
p.engines = u.Param()
if engine == 'ePIE':
	p.engines.engine00 = u.Param()
	p.engines.engine00.name = 'ePIE'
	p.engines.engine00.numiter = 500
	p.engines.engine00.numiter_contiguous = 5

elif engine == 'DMML':
	p.engines.engine00 = u.Param()
	p.engines.engine00.name = 'DM'
	p.engines.engine00.numiter = 50
	#p.engines.engine00.probe_support = 1.
	p.engines.engine00.numiter_contiguous = 1
	p.engines.engine00.probe_update_start = 1
	p.engines.engine00.update_object_first = True
	# #p.engines.engine00.fourier_relax_factor = .1
	# p.engines.engine00.probe_center_tol = 1

	# Reconstruction parameters
	#p.engines.engine01 = u.Param()
	#p.engines.engine01.name = 'ML'
	#p.engines.engine01.numiter = 15

P = Ptycho(p,level=5)
~~~~

**Comment by bjoernenders** [comment]
Hum. It shouldn't make a difference for now because syncing happens regardless of numiter_contiguous. Also I couldn't reproduce the error with my local code. Anyone else having this issuse?

**Comment by alexbjorling** [comment]
Exactly, looking at the code I couldn't see the problem either. 

The MoonFlowerScan test works fine under all circumstances, and the problem only occurs for the combo Nanomax data + DM retrieval. I guess my data is structured in the wrong way, but it's strange that ePIE is insensitive. 

Any idea of ways to troubleshoot this?

EDIT: I've uploaded the ptyd and script,
https://www.dropbox.com/sh/eq89yyocgcrtt4e/AACzxT9LMLk4fQ8tTJ-a6TV9a?dl=0

**Comment by bjoernenders** [comment]
I confirm this as a bug for now. I tried your script with both engine variants, and only DM with numiter_contiguous =1 works. The other options fail. EPIE fails with me too at only 100 iterations with both numiter_contiguous =1 and 5.

**Comment by bjoernenders** [comment]
I commited a fix: e6a4296. Instead of closing the issue, I wanted to point out that EPIE works for me in MPI and for the scan33.py, but not as a single process. Didn't look into that further, but maybe you can confirm that. Maybe some part of the operations in the communication part are necessary anyway.

**Comment by alexbjorling** [comment]
I confirm all of this, e6a4296 fixes the DM issue. Also, ePIE works for scan33.py with more than one process, but fails to reconstruct with one process and _default parameters_.

The thing about ePIE is that it is not really parallelizable, as noted in the code and described in the quoted [paper](https://doi.org/10.1364/OE.22.032082). What I mean is that running with a different number of processes actually changes the algorithm (each process has its own object and probe, and these are averaged regularly). 

For the scan33.py script, if I change the `random_order` parameter to `False,` it converges on one process in 20 iterations. For other data, it's fine on any number of processes with the default settings (well, with too many processes the edge effects between domains becomes a problem).

So I think (but don't know how to prove) that the ePIE problem is not an implementation error but a weakness in the algorithm.

**Comment by alexbjorling** [comment]
Also, @bjoernenders would you add the counter increment to `DM_simple` too?

**Comment by bjoernenders** [comment]
I guess you are right. Depending on the walk along points, EPIE is a different algorithm for each selection. For scans, where the positions are separated greater than the initial probe guess, you maybe need a 'guided random' walk feature that takes the points and calculates an irregular trajectory with enough overlap through them. At least that would maybe prevent the algorithm from failing, when having many scan points on a single node. Klaus Wakonig ( @wakonig ) used a cythonized metropolos algorithm for that in his thesis. Maybe you wish to acquire both his thesis (very interesting) and the cython code from him. He is at PSI now.

**Comment by alexbjorling** [comment]
Sounds very interesting, I'll make sure to get my hands on his thesis. Thanks for fixing this, the issue can be closed as far as I'm concerned.
