### ISSUE TITLE
Possible bug in the View class

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#74]
While working with my 3D `Storage`s and `View`s, I found some very weird behavior which I can also reproduce for 2D objects on the `master` branch.

For certain combinations of `psize` and `coord`, getting a view on a storage like `S[V]` returns nonsense. Reformatting the `Storage` alternately gives two incorrect views (see below). Are there some constraints on `psize`, `coord`, `shape`, etc, that I have missed? 

Code:
~~~
from ptypy.core import Container, View
import numpy as np

# The following works with psize = .2 or .05 but not .1, and with center = 54.7 or 54.8 but not 54.75
psize = .1
center = np.array([ 54.75,  54.75])
shape = (84,75)

C = ptypy.core.Container(data_dims=2)
S = C.new_storage(shape=128, padonly=False, psize=psize)
V = View(container=C, storageID=S.ID, coord=center, 
                     shape=shape, psize=psize)

for i in range(10):
    print 'S[V].shape = %s,'%str(S[V].shape)
    S.reformat()
print 'S.shape = %s'%str(S.shape)
~~~

Output:
~~~
S[V].shape = (0, 0),
S[V].shape = (0, 0),
S[V].shape = (84, 74),
S[V].shape = (84, 0),
S[V].shape = (84, 74),
S[V].shape = (84, 0),
S[V].shape = (84, 74),
S[V].shape = (84, 0),
S[V].shape = (84, 74),
S[V].shape = (84, 0),
S.shape = (1, 84, 75)

~~~

**Comment by bjoernenders** [comment]
I confirm this bug. Thanks for reporting (Although the script above does not execute as ptypy is not imported).
A long time ago, it took me a while to stabilize this reformatting issue. I will investigate this and get back to you. Maybe this should be a part of unit testing too.

**Comment by alexbjorling** [comment]
Bumping this bug (of which I have no memory!). Will also try to look into it.

**Comment by alexbjorling** [comment]
OK the problem here is that if pcoord is right between two pixels, rounding becomes unpredictable and all goes bad. Filed a PR with a workaround.
