### ISSUE TITLE
ptypy > core > geometry > _keV2m

### ISSUE THREAD

**Issue by cmkewish** [ptycho/ptypy#80]
Hi Bjoern,

I have a quick question: in PtyPy > core > geometry module, why is the hardcoded conversion of photon energy in keV to wavelength in meters:

`_keV2m = 1.240597288e-09`

instead of using the more common value:

`hc = 1.23984193e-09 keV*m` ?

**Comment by bjoernenders** [comment]
That is a good question. I don't recall how I came up with that number. It cold be historical reasons. 
 ``1.23984193e-09`` is even on wikipedia. Are you used working with git on a locked master branch? If not, I suggest that you commit a fix to get used to it. If you are used to the procedure and think that is an unnecessary exercise, I can do a quick fix.

**Comment by cmkewish** [comment]
OK I will try to work out how to submit the changed file.

**Comment by bjoernenders** [comment]
Fix was accepted.
