### ISSUE TITLE
How to generate my own diffraction patterns?

### ISSUE THREAD

**Issue by kdatta6** [ptycho/ptypy#82]
Hello Ptypy team,

I'm trying to generate my own diffraction pattern .ptyd files from input images that act as the sample.  I saw that the MoonFlowerScan class does exactly this, using the moon as the probe and the flower image as the sample.  In fact, after running the MoonFlowerScan class and generating a .ptyd file, I can reconstruct the original images of the moon and the flowers using Ptypy's difference map algorithm.

Now, if I change the code so that it instead of using the flower image, I use the tree image as the sample, I can create a new .ptyd file.  However, when I try to reconstruct the moon and the tree image using difference map, the algorithm no longer converges properly.

So, based off of this, I have a few questions:
1.  Is there an easier way to create my diffraction images other than modifying the MoonFlowerScan class (or creating another class similar to MoonFlowerScan)?
2.  Any thoughts on why I cannot reconstruct the tree image even though I can reconstruct the flower image?

Please let me know if anything is unclear.  Thank you for any help you can provide.

-Kaushik

**Comment by bjoernenders** [comment]
Hello Kaushik,

in order to help you, please append the modified PtyScan subclass and 
the reconstruction script. Thanks!

And yes you can create you own .ptyd in a very simple way with your own 
simulation code. Just mimic the structure of the ptyd file in form of a 
dict and use ptypy.io.h5write to create an h5 compatible format. Than 
you can use PtydScan to feed the data into the machine.

Best,

Bjoern

**Comment by kdatta6** [comment]
Hi Bjoern,

In order to generate my new .ptyd file, the only thing I changed in data.py's MoonFlowerScan class was line 1396.  Instead of:
`self.obj = resources.flower_obj(frame)`
I used the line:
`self.obj = resources.tree_obj(frame)`
so that it uses the tree image as the sample in the experiment.

I then ran:
`sudo python setup.py install`
to make sure the code was updated.

Next, to create my .ptyd file, I used the following script:
```python
# ptyd file generation script
import sys
import time
import ptypy
from ptypy import utils as u
                                                                    
u.verbose.set_level(3)
                                                                     
data = u.Param()
data.dfile = 'sample.ptyd'
data.shape = 128
data.num_frames = 100
data.save = 'append'
data.label = None
data.psize = 172e-6
data.energy = 6.2
data.center = (64, 64)
data.distance = 7
data.auto_center = None
data.rebin = None
data.orientation = None
                                                                      
MF = ptypy.core.data.MoonFlowerScan(pars=data)
MF.initialize()

for i in range(2):  
    msg = MF.auto(100)                                                
    u.verbose.logger.info(u.verbose.report(msg), extra={'allprocesses': True})
```

Then, to reconstruct the probe and sample, I used the following script:
```python
# reconstruction script using difference map
import ptypy
from ptypy.core import Ptycho
from ptypy import utils as u
import ptypy.simulations as sim
import numpy as np
import time
import sys

p = u.Param()

p.io.home = "./test_sample"
p.io.run = None
p.io.autosave = u.Param()
p.io.autosave.interval = 20
p.io.autoplot = False

p.scans = u.Param()
p.scans.MF = u.Param()
p.scans.MF.data= u.Param()
p.scans.MF.data.source = './sample.ptyd'
p.scans.MF.data.dfile = './sample.ptyd'

p.engine = u.Param()                                                               
p.engine.common = u.Param()
p.engine.common.numiter = 100
p.engine.common.numiter_contiguous = 1
p.engine.common.probe_support = 0.7
p.engine.common.probe_inertia = 0.01
p.engine.common.object_inertia = 0.1
p.engine.common.obj_smooth_std = 20
p.engine.common.clip_object = None
p.engine.common.probe_update_start = 2

p.engine.DM = u.Param()
p.engine.DM.name = "DM"
p.engine.DM.alpha = 1 
p.engine.DM.update_object_first = True
p.engine.DM.overlap_converge_factor = 0.05
p.engine.DM.overlap_max_iterations = 100
p.engine.DM.fourier_relax_factor = 0.1

p.engines = u.Param()
p.engines.engine00 = u.Param()
p.engines.engine00.numiter = 100
p.engines.engine00.name = 'DM'
p.engines.engine00.fourier_relax_factor = 0.05

u.verbose.set_level(3)

P = Ptycho(p,level=5)
```
Unlike with the flower image, when I ran with the tree image, it did not converge properly using difference map (the reconstructed image is just noise).  Please let me know if you have any thoughts on what might be wrong.

By the way, thanks for the instructions on how to create my own .ptyd files, but I think you assume that I already have some diffraction images that I want to convert into the .ptyd format.  That's not currently the case.  For now, I'm trying to take .png images and use them as samples in order to create diffraction patterns using Ptypy.  This is the reason I'm playing around with the images being input into the MoonFlowerScan class.  If you have any pointers on how the MoonFlowerScan class creates its diffraction patterns, that would also be useful.

Thanks again for any help, Bjoern.

**Comment by bjoernenders** [comment]
The treefile wasn't read in correctly. See fix a8c6af6. This is not a complex object, just absorbing in the way that you would use it. Hope that helps.

Ptypy has also fully equipped for simulation and generating data. Including different types of detectors. Have a look at the SimScan class for that. Unfortunately I have not yet time to write an entry for the tutorials. But the basic principle is, that it will read parameters for illumination, object etc. and will use a Ptycho instance internally to generate the model and then do a simple forward propagation. I guess it is a good address to find out how to use ptypy for simulation.

**Comment by kdatta6** [comment]
Thank you for the help, Bjoern.  With the fix, when I reconstruct the object transmission function, the amplitude has high contrast, but there's no contrast in the phase- every pixel has the same phase.  However, at least it is converging and I'm no longer seeing just noise.  I will try playing around with the  ptypy/resources/__init__.py file to see if the phase contrast can be improved.

I also appreciate the pointer to the SimScan class.  I will look into it!

**Comment by bjoernenders** [comment]
I am not surprised, as there is no phase in tree_obj function. See my first reply from before. 

Also please have a look at the examples in the `template/` directory. A large portion are just simulation, e.g. `ptypy_cSAXS_PseudoBone_6p2keV.py`

Good luck.

**Comment by bjoernenders** [comment]
I close this issue now.
