### ISSUE TITLE
How to run multimode reconstructions?

### ISSUE THREAD

**Issue by alexbjorling** [ptycho/ptypy#88]
This question belongs in a user forum rather than here, but posting anyway.

I am reconstructing fly scans, and would like to use multiple illumination modes to soak up the smearing. When I specify `p.scans.myscan.coherence.num_probe_modes = 3` I get three identical probes with DM. With ML they start changing very slightly compared to each other.

Am I doing something wrong or is this just how my data reconstructs?

**Comment by aaron-parsons** [comment]
Hi Alex,

I found this too, but that if you add the .diversity stuff to the illumination then they diverge with both. If they all start as the same thing then you just get a relative scaling, but if they have different roughness they go their own way.

Not sure what the actually algorithm mechanics is for this, but the .diversity makes it work...

Aaron



________________________________

**Comment by alexbjorling** [comment]
Ah, thanks! That makes me realize I have to read the paper again. What do you typically specify, just the initial powers?

**Comment by aaron-parsons** [comment]
I usually do something like:
p.scan.illumination.diversity.power = (0.8,0.2)
p.scan.illumination.diversity.noise = (2.0,3.0)

and then fiddle from there based on which beamline/dataset it is.

But something like this would normally converge.
________________________________

**Comment by alexbjorling** [comment]
OK thanks Aaron, I'll play with this.

And sorry to abuse the issue tracker for user tips. We could consider a user mailing list I guess.

**Comment by pierrethibault** [comment]
I'd actually mark this as a bug. Turning on modes without diversity is mathematically meaningless, so there should be a reasonable hard-coded default.

**Comment by alexbjorling** [comment]
This relates to #4

**Comment by aaron-parsons** [comment]
Just reviewing the tickets for the release, and had a question about this. Although I agree with Pierre that modes without diversity is meaningless, diversity here is actually a preparation-side parameter, iwth coherence being a reconstruction side one. If I were to do this on a real beamline, I probably in most cases would be starting from a pre-known probe (which I would set from an array). So maybe we could instead just make a warning that, if starting from a simulated probe, with a number of modes>1, should be raised. It'll still reconstruct, but at least the end-user gets a heads up that it will most likely fail.

Sound good?

**Comment by bjoernenders** [comment]
I agree with Aaron here. Should be a warning and called out by the scan model.

**Comment by aaron-parsons** [comment]
OK this is done now. Will move on to #152 and close this.
